### PR TITLE
Add rare candy and stardust french translation

### PR DESCRIPTION
**Pull request by na-ji**

### CODE REVIEW

**Comment by na-ji** [comment]
ping @dandesousa

**Comment by dandesousa** [comment]
Thanks for this, had missed it!

**Comment by dandesousa** [comment]
Apologize and I will look into updating my notifications to support this better

**Comment by dandesousa** [comment]
@na-ji there's seems to be some conflict with #10 -- I'm inclined to take this one but do you have any comments on the difference

**Comment by na-ji** [comment]
There are some mistakes on #10, rare candies are "super bonbons" in French

**Comment by na-ji** [comment]
"baies rares" does not even exist

**Review by dandesousa — APPROVED** [review]

**Comment by dandesousa** [comment]
Thanks for your contribution -- I'll get this merged in tonights update

**Comment by dandesousa** [comment]
And again sorry about the delay -- my notifications were messed up -- but now I should see all the PRs on this and I'll get them merged the week they are submitted

**Pull request merged**
